---
swagger: "2.0"
info:
  description: "API for dashboard with my diabetes data"
  version: "0.0.0"
  title: "Diabetes Dashboard API"
  contact:
    name: "Doug Warren"
    url: ""
    email: "git@dpw67.oib.com"
paths: {}
definitions: {}
