//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DefaultAPI: APIBase {
    /**
     
     - parameter moment: (body) Moment to add to the log 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addMoment(moment moment: NewMoment, completion: ((data: Moment?, error: ErrorType?) -> Void)) {
        addMomentWithRequestBuilder(moment: moment).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     - POST /moments
     - Creates a new moment in the log.  Duplicates are allowed
     - examples: [{contentType=application/json, example={
  "name" : "aeiou",
  "id" : 123456789,
  "tag" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "type" : "aeiou",
  "value" : "aeiou"
}}]
     
     - parameter moment: (body) Moment to add to the log 

     - returns: RequestBuilder<Moment> 
     */
    public class func addMomentWithRequestBuilder(moment moment: NewMoment) -> RequestBuilder<Moment> {
        let path = "/moments"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = moment.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<Moment>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

}
