//
// InfoAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class InfoAPI: APIBase {
    /**
     
     returns basic info of the server
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func infoGet(completion: ((error: ErrorType?) -> Void)) {
        infoGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     returns basic info of the server
     
     - GET /info

     - returns: RequestBuilder<Void> 
     */
    public class func infoGetWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/info"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
