//
// MomentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class MomentAPI: APIBase {
    /**
     
     Add a new moment to the log
     
     - parameter moment: (body) Moment to add to the log 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addMoment(moment moment: NewMoment, completion: ((data: Moment?, error: ErrorType?) -> Void)) {
        addMomentWithRequestBuilder(moment: moment).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Add a new moment to the log
     
     - POST /moments
     - Creates a new moment in the log. Duplicates are allowed
     - examples: [{contentType=application/json, example={
  "photoUrls" : [ "aeiou" ],
  "name" : "check",
  "tag" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "momentId" : 123456789,
  "type" : "aeiou",
  "category" : {
    "name" : "aeiou",
    "id" : 123456789
  },
  "complete" : true,
  "value" : "aeiou",
  "tags" : [ {
    "name" : "aeiou",
    "id" : 123456789
  } ],
  "status" : "aeiou"
}}]
     
     - parameter moment: (body) Moment to add to the log 

     - returns: RequestBuilder<Moment> 
     */
    public class func addMomentWithRequestBuilder(moment moment: NewMoment) -> RequestBuilder<Moment> {
        let path = "/moments"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = moment.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<Moment>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     delete a specific moment by ID
     
     - parameter momentId: (path) ID of moment to delete 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteMoment(momentId momentId: Int, completion: ((error: ErrorType?) -> Void)) {
        deleteMomentWithRequestBuilder(momentId: momentId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     delete a specific moment by ID
     
     - DELETE /moments/{momentId}
     - deletes a single moment based on the ID supplied
     
     - parameter momentId: (path) ID of moment to delete 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteMomentWithRequestBuilder(momentId momentId: Int) -> RequestBuilder<Void> {
        var path = "/moments/{momentId}"
        path = path.stringByReplacingOccurrencesOfString("{momentId}", withString: "\(momentId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Find moment by ID
     
     - parameter momentId: (path) ID of moment to fetch 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func findMomentById(momentId momentId: Int, completion: ((data: Moment?, error: ErrorType?) -> Void)) {
        findMomentByIdWithRequestBuilder(momentId: momentId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Find moment by ID
     
     - GET /moments/{momentId}
     - Returns a moment by on ID, if the user does not have access to the moment
     - examples: [{contentType=application/json, example={
  "photoUrls" : [ "aeiou" ],
  "name" : "check",
  "tag" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "momentId" : 123456789,
  "type" : "aeiou",
  "category" : {
    "name" : "aeiou",
    "id" : 123456789
  },
  "complete" : true,
  "value" : "aeiou",
  "tags" : [ {
    "name" : "aeiou",
    "id" : 123456789
  } ],
  "status" : "aeiou"
}}, {contentType=application/xml, example=<null>
  <momentId>123456</momentId>
  <name>check</name>
  <tag>string</tag>
  <type>string</type>
  <time>2000-01-23T04:56:07.000Z</time>
  <value>string</value>
  <photoUrls>string</photoUrls>
  <status>string</status>
  <complete>true</complete>
</null>}]
     - examples: [{contentType=application/json, example={
  "photoUrls" : [ "aeiou" ],
  "name" : "check",
  "tag" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "momentId" : 123456789,
  "type" : "aeiou",
  "category" : {
    "name" : "aeiou",
    "id" : 123456789
  },
  "complete" : true,
  "value" : "aeiou",
  "tags" : [ {
    "name" : "aeiou",
    "id" : 123456789
  } ],
  "status" : "aeiou"
}}, {contentType=application/xml, example=<null>
  <momentId>123456</momentId>
  <name>check</name>
  <tag>string</tag>
  <type>string</type>
  <time>2000-01-23T04:56:07.000Z</time>
  <value>string</value>
  <photoUrls>string</photoUrls>
  <status>string</status>
  <complete>true</complete>
</null>}]
     
     - parameter momentId: (path) ID of moment to fetch 

     - returns: RequestBuilder<Moment> 
     */
    public class func findMomentByIdWithRequestBuilder(momentId momentId: Int) -> RequestBuilder<Moment> {
        var path = "/moments/{momentId}"
        path = path.stringByReplacingOccurrencesOfString("{momentId}", withString: "\(momentId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Moment>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Returns all moments
     
     - parameter tags: (query) tags to filter by (optional)
     - parameter limit: (query) maximum number of results to return (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func findMoments(tags tags: [String]?, limit: Int?, completion: ((data: [Moment]?, error: ErrorType?) -> Void)) {
        findMomentsWithRequestBuilder(tags: tags, limit: limit).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Returns all moments
     
     - GET /moments
     - Returns all moments
     - examples: [{contentType=application/json, example=[ {
  "photoUrls" : [ "aeiou" ],
  "name" : "check",
  "tag" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "momentId" : 123456789,
  "type" : "aeiou",
  "category" : {
    "name" : "aeiou",
    "id" : 123456789
  },
  "complete" : true,
  "value" : "aeiou",
  "tags" : [ {
    "name" : "aeiou",
    "id" : 123456789
  } ],
  "status" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <momentId>123456</momentId>
  <name>check</name>
  <tag>string</tag>
  <type>string</type>
  <time>2000-01-23T04:56:07.000Z</time>
  <value>string</value>
  <photoUrls>string</photoUrls>
  <status>string</status>
  <complete>true</complete>
</null>}]
     - examples: [{contentType=application/json, example=[ {
  "photoUrls" : [ "aeiou" ],
  "name" : "check",
  "tag" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "momentId" : 123456789,
  "type" : "aeiou",
  "category" : {
    "name" : "aeiou",
    "id" : 123456789
  },
  "complete" : true,
  "value" : "aeiou",
  "tags" : [ {
    "name" : "aeiou",
    "id" : 123456789
  } ],
  "status" : "aeiou"
} ]}, {contentType=application/xml, example=<null>
  <momentId>123456</momentId>
  <name>check</name>
  <tag>string</tag>
  <type>string</type>
  <time>2000-01-23T04:56:07.000Z</time>
  <value>string</value>
  <photoUrls>string</photoUrls>
  <status>string</status>
  <complete>true</complete>
</null>}]
     
     - parameter tags: (query) tags to filter by (optional)
     - parameter limit: (query) maximum number of results to return (optional)

     - returns: RequestBuilder<[Moment]> 
     */
    public class func findMomentsWithRequestBuilder(tags tags: [String]?, limit: Int?) -> RequestBuilder<[Moment]> {
        let path = "/moments"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "tags": tags,
            "limit": limit
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[Moment]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

    /**
     
     Add a new moment to the log
     
     - parameter moment: (body) Moment to be updated in the log 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateMoment(moment moment: NewMoment, completion: ((data: ErrorModel?, error: ErrorType?) -> Void)) {
        updateMomentWithRequestBuilder(moment: moment).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Add a new moment to the log
     
     - PUT /moments
     - Creates a new moment in the log. Duplicates are allowed
     - examples: [{contentType=application/json, example={
  "code" : 123,
  "message" : "aeiou"
}}]
     
     - parameter moment: (body) Moment to be updated in the log 

     - returns: RequestBuilder<ErrorModel> 
     */
    public class func updateMomentWithRequestBuilder(moment moment: NewMoment) -> RequestBuilder<ErrorModel> {
        let path = "/moments"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = moment.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<ErrorModel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: true)
    }

}
