//
// MomentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class MomentAPI: APIBase {
    /**
     
     Find moments by ID
     
     - parameter id: (path) ID of moment to use 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getMomentsById(id id: [String], completion: ((data: [Moment]?, error: ErrorType?) -> Void)) {
        getMomentsByIdWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Find moments by ID
     
     - GET /moments/{id}
     - Returns moments based on ID
     - examples: [{contentType=application/json, example=[ {
  "id" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "type" : "aeiou",
  "value" : "aeiou"
} ]}]
     
     - parameter id: (path) ID of moment to use 

     - returns: RequestBuilder<[Moment]> 
     */
    public class func getMomentsByIdWithRequestBuilder(id id: [String]) -> RequestBuilder<[Moment]> {
        var path = "/moments/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[Moment]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     returns all moments
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func momentsGet(completion: ((data: [Moment]?, error: ErrorType?) -> Void)) {
        momentsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     returns all moments
     
     - GET /moments
     - examples: [{contentType=application/json, example=[ {
  "id" : "aeiou",
  "time" : "2000-01-23T04:56:07.000+0000",
  "type" : "aeiou",
  "value" : "aeiou"
} ]}]

     - returns: RequestBuilder<[Moment]> 
     */
    public class func momentsGetWithRequestBuilder() -> RequestBuilder<[Moment]> {
        let path = "/moments"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[Moment]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     deletes a specific moment with the identified id
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func momentsIdDelete(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        momentsIdDeleteWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     deletes a specific moment with the identified id
     
     - DELETE /moments/{id}
     - examples: [{contentType=application/json, example="{}"}]

     - returns: RequestBuilder<AnyObject> 
     */
    public class func momentsIdDeleteWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/moments/{id}"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     saves a specific moment with the identified id
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func momentsIdPost(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        momentsIdPostWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     saves a specific moment with the identified id
     
     - POST /moments/{id}
     - examples: [{contentType=application/json, example="{}"}]

     - returns: RequestBuilder<AnyObject> 
     */
    public class func momentsIdPostWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/moments/{id}"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     saves a specific moment with the identified id
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func momentsIdPut(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        momentsIdPutWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     saves a specific moment with the identified id
     
     - PUT /moments/{id}
     - examples: [{contentType=application/json, example="{}"}]

     - returns: RequestBuilder<AnyObject> 
     */
    public class func momentsIdPutWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/moments/{id}"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<AnyObject>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: true)
    }

}
