//
// Moment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Moment: JSONEncodable {

    public var momentId: Int?
    public var name: String?
    public var tag: String?
    public var _type: String?
    public var time: NSDate?
    public var value: String?
    public var photoUrls: [String]?
    public var category: Category?
    public var tags: [Tag]?
    /** Moment status in the log */
    public var status: String?
    public var complete: Bool?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["momentId"] = self.momentId
        nillableDictionary["name"] = self.name
        nillableDictionary["tag"] = self.tag
        nillableDictionary["type"] = self._type
        nillableDictionary["time"] = self.time?.encodeToJSON()
        nillableDictionary["value"] = self.value
        nillableDictionary["photoUrls"] = self.photoUrls?.encodeToJSON()
        nillableDictionary["category"] = self.category?.encodeToJSON()
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["status"] = self.status
        nillableDictionary["complete"] = self.complete
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
